### ISSUE TITLE
Do we really need to use the Daskhub Tosca template?

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo-eosc#12]
While working on a Tosca template for every people using EGI to be able to easily deploy a Daskhub on top of EOSC sound really nice, I'm not sure we really need it for now, and even later.

As we are directly working on values.yaml files and helm commands at some points of the deployment of our infrastructure, just a plain Kubernetes cluster with Helm should be enough.

Maybe once all things in our deployment are settle down, we should work on the template, but for now as we are more prototyping things, I'm feeling this adds some noise.

Any thoughts?

**Comment by sebastian-luna-valero** [comment]
Closing as obsolete. We have been working with a plain k8s cluster and deploying DaskHub with helm directly.

However, I would like to contribute back to the DaskHub Tosca template in IM at some point.
