### ISSUE TITLE
Modules version mismatch

### ISSUE THREAD

**Issue by j34ni** [pangeo-data/pangeo-eosc#20]
It seems that there are now different versions of packages on the clients, schedulers and workers

>/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/client.py:1274: VersionMismatchWarning: Mismatched versions found
>
>+-------------+----------+-----------+--------------------------+
>| Package     | client   | scheduler | workers                  |
>+-------------+----------+-----------+--------------------------+
>| dask        | 2022.7.0 | 2022.7.0  | {'2022.8.0', '2022.7.0'} |
>| distributed | 2022.7.0 | 2022.7.0  | {'2022.8.0', '2022.7.0'} |
>| numpy       | 1.23.1   | 1.23.1    | {'1.23.2', '1.23.1'}     |
>+-------------+----------+-----------+--------------------------+
>  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))

Could it be that some use the version of the pangeo-notebook docker image that was available at the time of deployment of the infrastructure, whereas newly created workers use the latest version of the same image ?

**Comment by guillaumeeb** [comment]
I've also observed the same warning.

> Could it be that some use the version of the pangeo-notebook docker image that was available at the time of deployment of the infrastructure, whereas newly created workers use the latest version of the same image ?

I think that is correct:
- Client and Scheduler are running inside the notebook Kernel, using the deployment time Pangeo image.
- Workers: some are using initial Pangeo image, others are using a more up to date one. This is weird!

I didn't dig into it, but thinking of it, I wonder if we are not in some caching situation of Docker image on underlying openstack VMs. Perhaps the first deployed VM has an old Pangeo image which is never refreshed, and when scaling Workers to VMs that didn't have this Pangeo image, a new one got pulled there.

I'm not sure how we can force notebook servers or Dask workers to really pull the last image, there might be some configuration options on Daskhub/Jupyterhub helm charts, or in Dask gateway, to allow this. Another possibility would be not to use `latest` tag in our Helm configuration.

**Comment by sebastian-luna-valero** [comment]
Hi,

Indeed, I think this is controlled in the following section of `values.yaml` for `helm`:

```yaml
  singleuser:
    image:
      name: pangeo/ml-notebook
      tag: latest
```

And the `version` option of the `helm` command below:


```bash
sudo helm upgrade daskhub daskhub \
    --repo=https://helm.dask.org \
    --install \
    --cleanup-on-fail \
    --create-namespace \
    --namespace daskhub \
    --version 2022.6.0 \
    --values values.yaml
```

Both in: https://github.com/pangeo-data/pangeo-eosc/blob/main/EGI.md should be pinned consistently.

Best regards,
Sebastian

**Comment by j34ni** [comment]
It seems that simply stopping and restarting the server from Jupyter's "Hub control pannel" fixes it

I guess that discrepancies will always happen if the server was started before the latest pangeo-notebook docker image (used by the newly created workers) was released

So, unless you still have the same problem and it does not disappear after restarting your server, there is nothing to change for that in the deployment and we can close this issue

**Comment by guillaumeeb** [comment]
Thanks @j34ni for testing this.

So there is two solutions: 

- Use latest Docker image and just restart the notebook server if we run into this issue.
- Pin the Docker images for both notebook server and workers.
