### ISSUE TITLE
CLIVER workshop : EGI  checkin setup and use of foss4g jupyter-hub instance . 

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#24]
[CLIER workshop](https://www.clivar.org/events/arctic-processes-cmip6-bootcamp) will use pangeo-eosc infrastructure.  The workshop starts on 12th October. To prepare, we asked all students and mentors to test connect our foss4g instance.  
Following the [foss4g tutorial](https://pangeo-data.github.io/foss4g-2022/before/setup.html) they will enrolle to [vo.pangeo.eu https://aai-dev.egi.eu/registry/co_petitions/start/coef:290 ](https://aai-dev.egi.eu/registry/co_petitions/start/coef:290 ) and 
they will run xarray tutorial (without dask) using [https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/hub/user-redirect/git-pull?repo=https%3A//github.com/pangeo-data/foss4g-2022&urlpath=lab/tree/foss4g-2022/tutorial/pangeo101/&branch=main](https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/hub/user-redirect/git-pull?repo=https%3A//github.com/pangeo-data/foss4g-2022&urlpath=lab/tree/foss4g-2022/tutorial/pangeo101/&branch=main)

@j34ni @annefou @guillaumeeb @sebastian-luna-valero 
We will have requests from enrolling the system from them, I would like to keep track on who made request, who haven't, without mixing up with our foss4g student.  

I'll have google sheet for list of CLIVER students we may need to find a way to keep track on who are enrolled for vo.pangeo for which project?

**Comment by j34ni** [comment]
@tinaok @annefou @guillaumeeb @sebastian-luna-valero

We asked participants to the FOSS4G workshop who enrolled in the vo.notebooks.egi.eu VO to indicate in the “statement for purpose” that they registered to be able “To execute Jupyter notebooks at the Pangeo 101 workshop in the frame of the FOSS4G-2022 conference”.

This “statement for purpose” question is not asked when enrolling in the vo.pangeo.eu Virtual Organisation: maybe should we add it? 

I do not know who can change the form, or how difficult it would be, but that would make it clear who enrolls and why, and not mix participants to various events

**Comment by sebastian-luna-valero** [comment]
The "statement for purpose" has now been added to the `vo.pangeo.eu` in EGI Check-In.

FYI: there are a few petitions to join the VO in `aai-dev.egi.eu`, but surely they haven't seen the statement for purpose, as it was added after they requested to enroll. Would you accept their petition to enroll as they are, or ask them to enroll again?

**Comment by sebastian-luna-valero** [comment]
I believe that's not possible, but in https://aai-dev.egi.eu/ you can go to People -> Petitions and get a list of pending petitions, so you know who's recently asked to enroll the VO.

I hope that helps.

**Comment by sebastian-luna-valero** [comment]
Hi,

> enrolling, and accepting petition is going well.

Good to know, thanks!

> Workshop attendee are asked to click https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/user/todaka/lab/workspaces/auto-k/tree/foss4g-2022/tutorial/pangeo101 and some have err messages.

Regarding the first error message, it looks like users are trying to access https://notebooks.egi.eu/ rather than https://pangeo-foss4g.vm.fedcloud.eu/, are we certain that they haven't clicked the wrong URL?

Regarding the second error message, this normally happens when the user is not a member of the `vo.pangeo.eu` Virtual Organisation.

Sorry if I am missing something basic here, but why should a user go to https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/user/todaka/lab/workspaces/auto-k/tree/foss4g-2022/tutorial/pangeo101 rather than cloning https://github.com/pangeo-data/foss4g-2022/ after logging into https://pangeo-foss4g.vm.fedcloud.eu/ and then do `cd tutorial/pangeo101`?

Best regards,
Sebastian

**Comment by annefou** [comment]
Concerning the infra for the CLIVAR Bootcamp: Do we also have storage?

**Comment by guillaumeeb** [comment]
@sebastian-luna-valero the link we give is the following one:

https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/hub/user-redirect/git-pull?repo=https%3A//github.com/pangeo-data/foss4g-2022&urlpath=lab/tree/foss4g-2022/tutorial/pangeo101/&branch=main

It does exactly what you described. @tinaok probably copied the url in her browser after the redirection.

**Comment by guillaumeeb** [comment]
@annefou we've got the same storage as for Foss4g. Up to 10TB of object store I guess. Is this what you asked for?

**Comment by j34ni** [comment]
@tinaok 
Is the problem not that new users will not have already cloned the repo and hence the link fails because the folder does not exist?
Maybe should it be simply https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/

**Comment by guillaumeeb** [comment]
@j34ni with the link I gave above, Jupyter automatically clone the repo, really nice feature! This is the one we have in our Jupyter book doc.

**Comment by j34ni** [comment]
@tinaok 
I remember we had similar issues at FOSS4G (may not be exactly the same though) and the user never managed to get access. She had an extremely secure laptop which apparently nearly everything. She eventually used the binder alternative

**Comment by sebastian-luna-valero** [comment]
> Concerning the infra for the CLIVAR Bootcamp: Do we also have storage?

Please see:   https://github.com/pangeo-data/pangeo-eosc/issues/17#issuecomment-1259099227

Currently users are enrolling `vo.pangeo.eu` in `aai-dev.egi.eu`, so they don't have access to Object Storage.

The Pangeo VO admins (i.e. you guys, have 10 TB object storage available). Read-only access is available for regular users as well as it was done for the FOSS4G workshop.

On the other hand I am waiting for CESNET to provide details about limiting access to buckets created by users. There is an added complication regarding the translation of EGI accounts to local S3 credentials that we are discussing.

I hope that helps.

**Comment by sebastian-luna-valero** [comment]
Closing as obsolete.
