### ISSUE TITLE
Accessing an IM Dashboard deployed Kubernetes through a local client

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo-eosc#27]
Currently, in order to launch `kubectl` or `helm` commands on Kubernetes cluster deployed on EOSC through IM Dashboard, I connect on the front node VM using the pem file which can be downloaded, and the login `cloudadm`.  This is OK, but front nodes default configuration is a little rough, and I'm not an expert on how to improve it. In the last deployment, I don't have history and tab completion for example.

I noticed on the IM Dashboard "Outputs" of a deployment that there is a `kubeconfig` file. I decided to download it in order to run `kubectl` and `helm` commands from my local laptop. However, no luck:
```bash
$ kubectl get pods -n daskhub
Unable to connect to the server: dial tcp 147.251.21.227:6443: i/o timeout
$ telnet 147.251.21.227  6443
Trying 147.251.21.227...
telnet: Unable to connect to remote host: Connection timed out
```

Any idea why I can't connect to the kubernetes master or controler @sebastian-luna-valero?

**Comment by guillaumeeb** [comment]
> This is OK, but front nodes default configuration is a little rough, and I'm not an expert on how to improve it. In the last deployment, I don't have history and tab completion for example.

OK, just fixed that by running bash first to enter a proper scripting environment. But still curious if this is possible to interact remotely with Kubernetes.

**Comment by sebastian-luna-valero** [comment]
Yes, sorry, please enter `bash` after you ssh into the front-end node, and life will be simpler!

On the other hand, IM does not open port `6443` in OpenStack automatically. This was the case a while ago, but it creates a big security risk and it has been disabled. Could you please ssh into the front-end node and manage the cluster from there?

**Comment by guillaumeeb** [comment]
Ok fine by me!
