### ISSUE TITLE
Some user stuck in 'Approval ' and can't access to https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#30]
Following #24, 
Users who can connect https://pangeo-foss4g.vm.fedcloud.eu/jupyterhub/ are in following situation in EGI dashboard; 
<img width="259" alt="スクリーンショット 2022-10-05 10 45 27" src="https://user-images.githubusercontent.com/46813815/194020312-eb4484f8-491e-4fdd-a1db-70865de176bd.png">

But some who can't connect and they are stuck  in 

<img width="231" alt="スクリーンショット 2022-10-05 10 44 45" src="https://user-images.githubusercontent.com/46813815/194019803-f6e408aa-ee48-48c7-9f13-bc22fed9c42b.png">

What can I do to 'finalise' their request?
Thank you for your help! 
@sebastian-luna-valero

**Comment by sebastian-luna-valero** [comment]
Not sure why, sorry. I am double checking with the Check-In team.

**Comment by sebastian-luna-valero** [comment]
If the issue has not been solved by today 5pm, please delete/re-enroll the user.

**Comment by tinaok** [comment]
Hi @sebastian-luna-valero I sent you the user ID by e-mail 9th Oct around 11:00 
and looks all user is in 'Finalised' status.
