### ISSUE TITLE
Cliver workshop: object storage organisation

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#32]
Following conversation at #21 (for Cliver workshop's object storage organisation), I made this issue to discuss the object storage architecture adapted for workflow of cliver workshop.  

- During the workshop we'll have different (about 6, 7) working group.  
- Each working group probably use common input dataset.  
- Some data are already on cloud.  But if the data will be repeatedly accessed, it is not optimal to each time use the data from there, but better to create neighbouring cloud Zarr copy, in a optimised chunk for the computation.
- Some (especially observation ) are not on the cloud, we need to store them in neighbouring cloud.

**Comment by sebastian-luna-valero** [comment]
As it stands at the moment:
* members of `vo.pangeo.eu` in `aai.egi.eu` will have read/write access to object storage at CESNET.
* members of `vo.pangeo.eu` in `aai-dev.egi.eu` will have read-only access to object storage at CESNET.

Containers created as `public` will be readable by everybody, but only members of `vo.pangeo.eu` in `aai.egi.eu` can write to them.

By the way, @tinaok you are creating containers/buckets in OpenStack project `vo.pangeo.eu` but you should be using OpenStack project `vo.pangeo.eu-swift`.

**Comment by sebastian-luna-valero** [comment]
The link is: https://aai.egi.eu/registry/co_petitions/start/coef:386

The statement of purpose needs also to be filled out in there.

**Comment by guillaumeeb** [comment]
> members of vo.pangeo.eu in aai-dev.egi.eu will have read-only access to object storage at CESNET.

@sebastian-luna-valero I didn't get this, currently, they have read access to any buckets in vo.pangeo.eu or vo.pangeo.eu-swift even if the buckets are not public?

> @sebastian-luna-valero, If I understood correct attendee to be able to write in the tmp folder, they need to enroll the vo.pangeo.eu in aai.egi.eu.

@sebastian-luna-valero
- If they enroll on vo.pangeo.eu in aai.egi.eu, they won't be admin on compute or storage part of Openstack, right? 
- On object storage part, does that make a difference to be admin or just member of vo.pangeo.eu? There are admins, right?
- If they enroll on vo.pangeo.eu in aai.egi.eu they will be able to read, write, create or delete any buckets, correct?

If we want something else, we need to pursue #17, and test https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object-acl.html.

**Comment by sebastian-luna-valero** [comment]
> @sebastian-luna-valero I didn't get this, currently, they have read access to any buckets in vo.pangeo.eu or vo.pangeo.eu-swift even if the buckets are not public?

Maybe the table below clarify things:

![image](https://user-images.githubusercontent.com/5345517/194818582-2c18cef7-d4d5-44f0-b6c1-2e5fa95c6588.png)


Visit it [here](https://docs.google.com/spreadsheets/d/1mwDKzmlN3je5n7gVj9nq9mn4hNtbnEAKjrd0K4Vv4Vo/edit#gid=457135989) if you want to comment.

> If they enroll on vo.pangeo.eu in aai.egi.eu, they won't be admin on compute or storage part of Openstack, right?

Correct. See table above.

> On object storage part, does that make a difference to be admin or just member of vo.pangeo.eu? There are admins, right?

See the difference on the table above.

> If they enroll on vo.pangeo.eu in aai.egi.eu they will be able to read, write, create or delete any buckets, correct?

Any buckets on the "vo.pangeo.eu-swift" Object Store. See table above. This is what we are trying to solve in #17 .

I hope it helps.

**Comment by sebastian-luna-valero** [comment]
Closing as obsolete.
