### ISSUE TITLE
Which VM flavor to use for the CLIVAR workshop

### ISSUE THREAD

**Issue by sebastian-luna-valero** [pangeo-data/pangeo-eosc#34]
Hi,

Previously we have used the VM flavor `hpc.16core-64ram-ssd-ephem` which worked well for the FOSS4G workshop.

However, this time the amount of requested resources per user and the number of users are higher for the CLIVAR workshop. Using the same flavor `hpc.16core-64ram-ssd-ephem` will create a big number of VMs for the same Pangeo cluster. We should consider using the `hpc.30core-64ram` instead so we accommodate the same number of users with less VMs and save some overhead. See:

https://docs.google.com/spreadsheets/d/1mwDKzmlN3je5n7gVj9nq9mn4hNtbnEAKjrd0K4Vv4Vo/edit#gid=1376984822

Please let me know your thoughts.

Best regards,
Sebastian

**Comment by j34ni** [comment]
Using larger instances will make it easier to setup the infrastructure
However, in terms of performances with Dask, is it better to use large or small flavors?
Maybe should we run some benchmarks tests, probably after the CLIVAR workshop

**Comment by sebastian-luna-valero** [comment]
I believe we need to find a good balance between flavor size and the use of dask clusters.
Maybe it's too late to discuss this for CLIVAR and we need to benchmark later on.

**Comment by j34ni** [comment]
I managed to add several VMs to pangeo-clivar which now has 16 WNs + 1 front (this is the HPC flavor with 16vCPUs and 64GB RAM)

Anything beyond that fails with this message on openstack:

``No valid host was found. There are not enough hosts available.``

In total pangeo-clivar has 17*16=272vCPUs, and there is this other infrastructure that @guillaumeeb built which has 3*8=24vCPUs

So in practice we can only use 296 out of the 1736 vCPUs which are shown on the project...

**Comment by sebastian-luna-valero** [comment]
Thanks, I am reporting this to CESNET and will come back to you.

**Comment by sebastian-luna-valero** [comment]
While CESNET replies, could you please:
1. Delete VMs with `Error` state.
2. Try adding new nodes but in small batches (e.g. 5 at a time)?

**Comment by j34ni** [comment]
@sebastian-luna-valero 

1. I have deleted them in openstack, and that must have triggered something because they then appeared on the IM Dashboard (as "Failed") whereas before they were not even shown
2. I will try again, with a single VM to start with

**Comment by guillaumeeb** [comment]
Back to the original question, my feeling is that it's more a question of optimal ratio of memory per core in a Dask cluster (and in Jupyter notebooks) for our use cases. Having an infrastructure with ~2GiB per core seems a bit limited to me, but IIRC this is what we asked for. 

I guess for workshop, it's probably OK to have only 2GiB per core, and this allows to have more people working at the same time. For real applications, this will probably vary, but again it seems low to me.

> Using the same flavor hpc.16core-64ram-ssd-ephem will create a big number of VMs for the same Pangeo cluster

I don't think this is a problem. It depends on where the overhead you're talking about is.

**Comment by guillaumeeb** [comment]
@sebastian-luna-valero, In #21you said:

> I would be very much in favor of fixing the amount of vCPUS/RAM per dask worker so we have a predicable amount of capacity, to avoid capacity problems.

As @tinaok said, we want to be able to change configurations depending on our need. However, we can also [use profiles](https://gateway.dask.org/cluster-options.html#cluster-profiles), and always keep the same core/memory ratio. 

Even if we don't use profile, the idea would still be to have a "reference" ratio, that is used in general. If we change VM flavor, we should update this ratio to be 1 core each 2GiB of RAM.

**Comment by sebastian-luna-valero** [comment]
CESNET confirmed that we should be using the `elixir.16core-64ram` flavor for new nodes in the k8s cluster.

**Comment by guillaumeeb** [comment]
So it's a different flavor than the one we were using? Does this implies using im-client?

Also, does this mean that the underlying physical infrastructure is kind of separated front the one used for the flavor we were using?

**Comment by tinaok** [comment]
@sebastian-luna-valero 
> @tinaok @guillaumeeb @annefou @j34ni I guess at this point we have a definite number of attendees, so we can refine the total amount of capacity required?

Hi, I'm on site now, we will be 30 (22 student 8 mentor) tomorrow.  

Anne will start showing https://github.com/pangeo-data/clivar-2022 8:30 tomorrow morning.

**Comment by sebastian-luna-valero** [comment]
> So it's a different flavor than the one we were using? Does this implies using im-client?

It is, but I am checking OpenStack and expanding the cluster via IM Dashboard picks up the correct flavor `elixir.16core-64ram` automatically so no need to use `im-client`. 

> Also, does this mean that the underlying physical infrastructure is kind of separated front the one used for the flavor we were using?

It means that the new worker nodes added to the k8s cluster will still use 16 vCPU cores and 64 GB RAM, but they won't use SSD disks. I am sorry but CESNET didn't have the capacity available at the moment to allocate many more VMs with the previous flavor.

> Hi, I'm on site now, we will be 30 (22 student 8 mentor) tomorrow.

Thanks, please add as many `elixir.16core-64ram` worker nodes as possible. Once we hit the limit at CESNET we will figure out what capacity can be offered to each attendee.

> Anne will start showing https://github.com/pangeo-data/clivar-2022 8:30 tomorrow morning.

I hope all goes well!

**Comment by j34ni** [comment]
@annefou @tinaok @sebastian-luna-valero 
There are currently 20 WNs and everything is green (configured), so I would rather not fiddle with the infrastructure while the course is ongoing

**Comment by j34ni** [comment]
@tinaok 

These 20 WNs currently provide:
``20 * 16 = 320 vCPUs ``
and 
``20 * 64 = 1280 GB RAM``

Do you want to try to add more before the Dask session?

**Comment by tinaok** [comment]
> > It means that the new worker nodes added to the k8s cluster will still use 16 vCPU cores and 64 GB RAM, but they won't use SSD disks.
> 
> I think up to this point we never used SSD disk, at least for performance. For the workshops, they are clearly not needed.

User use NFS disk space, it think it is based on the SSD disk? and also when dask buffers extra memory to disk, which is also SSD.

**Comment by tinaok** [comment]
@j34ni 

> @tinaok
> 
> These 20 WNs currently provide: `20 * 16 = 320 vCPUs ` and `20 * 64 = 1280 GB RAM`
> 
> Do you want to try to add more before the Dask session?

memory is ok. 
Do we have 4 cores for each jupyterlab? Then 8 cores x 30 users so it should work for the tutorial of this morning.

**Comment by sebastian-luna-valero** [comment]
>  It seems that sdb is of rotational type, and not SSD

`/dev/sdb` is where the Ceph-based volume for NFS is mounted. I wouldn't expect this to be SSDs.

> I'm not sure about the Home directory. In any case this is another volume, not linked to the VM flavor. And SSD performance is not needed.

I believe home directories are using the default storage class configured by IM, which is NFS underneath
>  For the worker local disk, I don't think we need SSD performance for spilling during the workshops either.

That's great to know, thanks!

**Comment by tinaok** [comment]
> > User use NFS disk space, it think it is based on the SSD disk? and also when dask buffers extra memory to disk, which is also SSD.
> 
> I'm not sure about the Home directory. In any case this is another volume, not linked to the VM flavor. And SSD performance is not needed. For the worker local disk, I don't think we need SSD performance for spilling during the workshops either.
@guillaumeeb @sebastian-luna-valero 
I'm not sure.
Students are building their project.  So I do not know the size of data they will use during the workshop.  
Depending on the size of data that they will analyse this week and next week, it might spill to RAM of dask?
Or spill is already disabled?

**Comment by j34ni** [comment]
Users home directories are on /pv, which is on sdb

**Comment by j34ni** [comment]
and this is the information I found on /dev/sdb:

Vendor:               QEMU
Product:              QEMU HARDDISK
Revision:             2.5+
Compliance:           SPC-3
User Capacity:        999,653,638,144 bytes [999 GB]
Logical block size:   512 bytes
LU is thin provisioned, LBPRZ=0
Serial number:        39c4eac7-0987-4fef-bf3b-a30c1daacb93
Device type:          disk
Local Time is:        Wed Oct 12 07:32:12 2022 UTC
SMART support is:     Unavailable - device lacks SMART capability.

**Comment by j34ni** [comment]
@tinaok 
I did not check before but now I can see that there are still 16 jupyters, with 26 dask-schedulers and 150 dask-workers running
How did the infrastructure withstand the load?

**Comment by j34ni** [comment]
![Screenshot from 2022-10-12 17-24-24](https://user-images.githubusercontent.com/44261743/195383986-f6495a09-65ea-4930-b65c-de925ba596dd.png)
![Screenshot from 2022-10-12 17-24-05](https://user-images.githubusercontent.com/44261743/195383991-30a7c35e-668c-41b5-8bba-6a122b7a9292.png)

**Comment by tinaok** [comment]
@j34ni @sebastian-luna-valero @guillaumeeb 
Thank you very much,
We finished tutorial with dask part.  Except some user (about 3) had problem with starting dashboard when using local dask cluster, all went fine  Thank you very much,
We were rush to finish, and I didn't precise well to shutdown clusters from daskgateway, I hope it will have some timeout and cleaning.

**Comment by guillaumeeb** [comment]
> Depending on the size of data that they will analyse this week and next week, it might spill to RAM of dask?
Or spill is already disabled?

I don't think spilling is disabled, but it can work normal spinning disks too. Anyway, spilling is almost always bad, so if a workflow began to spill to disk, I think it should be optimized.

> I hope it will have some timeout and cleaning.

I'm not sure the idle timeout for Dask Gateway cluster has been set on this infrastructure. (https://github.com/pangeo-data/pangeo-eosc/blob/main/EGI.md?plain=1#L221).
