### ISSUE TITLE
Create acknowledgement statement for the usage of pangeo-eosc cloud

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#37]
Clivar bootcamp organisers proposed to add acknowledge comment for pangeo-eosc cloud.  
We can make add text that people can refer at acknowledgement.md or at Readme.md? 
Any special text from EGI & EOSC? @sebastian-luna-valero ?

**Comment by sebastian-luna-valero** [comment]
Checking this internally, and will report asap. Thanks!

**Comment by sebastian-luna-valero** [comment]
Could you please use:

> This work used advanced computing resources from the CESNET resource centre of the EGI federation. The services are co-funded by the EGI-ACE project (https://www.egi.eu/project/egi-ace/, grant number 101017567).

I can open a PR if you agree on its best location to be referenced.

**Comment by tinaok** [comment]
Thank you @sebastian-luna-valero, @annefou anyidia where is best for us to put these information ?

**Comment by annefou** [comment]
I put it in the README (https://github.com/pangeo-data/clivar-2022) and updated the acknowledgement statement we had at the top of our intro (https://pangeo-data.github.io/clivar-2022/intro.html). @sebastian-luna-valero let us know if you wish to have it in different places.

**Comment by sebastian-luna-valero** [comment]
Looks good to me, thanks!

Maybe we can close this issue and re-open if a change is necessary.

**Comment by sebastian-luna-valero** [comment]
Closing as obsolete.
