### ISSUE TITLE
jupyterlab git extension is missing

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#63]
```
(notebook) jovyan@jupyter-todaka:~$ mamba list |grep lab-git
jupyterlab-git            0.41.0             pyhd8ed1ab_1    conda-forge
(notebook) jovyan@jupyter-todaka:~$ 
```

In the mamba list, jupyterlab-git exist but in the web-interface, the jupyterlab-git extension does not exist.  Can it be because that jupyterlab version is 4.*? 
<img width="244" alt="スクリーンショット 2023-10-31 14 55 32" src="https://github.com/pangeo-data/pangeo-eosc/assets/46813815/3b4fd3b7-d1b8-4979-88b3-f3b935aa64cf">

**Comment by sebastian-luna-valero** [comment]
xref: https://github.com/pangeo-data/pangeo-docker-images/pull/469
