### ISSUE TITLE
Acknowledgement Pangeo-EOSC C-SCALE

### ISSUE THREAD

**Issue by acocac** [pangeo-data/pangeo-eosc#71]
@sebastian-luna-valero may I ask if how we should acknowledge the deployment of Pangeo-EOSC for trainings? @annefou and I got accepted a position paper related to the lessons learned from the 2023 Reproducibility Challenge. We would like to acknowledge the support of the C-SCALE project so happy to include details e.g. grant agreements if relevant. 

Finally, I suggest we indicate how to acknowledge within a dedicated section in the README file (e.g. after Training events).

**Comment by sebastian-luna-valero** [comment]
Congratulations @acocac!

I have just proposed a change with this request: https://github.com/pangeo-data/pangeo-eosc/pull/72

Could you please check?

Also, would it be possible to add your accepted paper to the README file on this repository as well?

Thanks!

**Comment by acocac** [comment]
Thank you! The acknowledgement section looks good to me. I'll add the paper once it's published (between Sept-Oct 2024).
