### ISSUE TITLE
How do we clean the unused resources

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#8]
I'm wondering if explicitly 'close ' jupyterlab ' (File-> Hub control panel -> Stop My Server) would it kill Dask Cluster started with Dask Gateway from that user's jupyterlab? Is it well linked?
If so we can teach people to 'close' jupyterlab ? And this can solve non used dask cluster + non used jupyterlab resources.

**Comment by guillaumeeb** [comment]
Tonight, I found a dask scheduler and worker pod started without any jupyter pod... So I guess Dask Gateway cluster are persistent upon Jupyterlab sops currently.

We should address that. This should apparently not be the case. It is said in https://gateway.dask.org/usage.html#shutdown-the-cluster:

> Alternatively, lingering cluster objects will be automatically shutdown when your client process closes. It’s good practice to explicitly clean things up, but it’s not strictly necessary. If you want clusters to persist longer than the lifetime of your client process, set shutdown_on_close=False when calling [Gateway.new_cluster()](https://gateway.dask.org/api-client.html#dask_gateway.Gateway.new_cluster).

Maybe we set it to False somewhere, did not have the time to look.

**Comment by sebastian-luna-valero** [comment]
Please let's include an explicit deletion of the dask cluster in the relevant notebooks to avoid issues:
https://gateway.dask.org/usage.html#shutdown-the-cluster

I have seen dask clusters lingering around even after the user session was ended.

**Comment by guillaumeeb** [comment]
I've done some tests, and by default, no matter what you do (stopping kernel, stopping Jupyter server, deleting cluster object, etc.), Dask clusters won't get stopped if you don't ask for it explicitly in the notebook.

So @tinaok we should definitly add the shutdown to the notebook.

A quick snippet so that one user cleans its running clusters:

```python
for cluster in gateway.list_clusters():
    cluster = gateway.connect(cluster.name)
    cluster.shutdown()
```

On admin side, we can clear things up using:

```
sudo kubectl delete pods -n daskhub <scheduler pod name>
```

However, we would need to know to who is a scheduler belonging. This can be found in some logs, but is not easy.

I'll open an issue on dask-gateway to have some feedback.

**Comment by guillaumeeb** [comment]
I've posted a comment here: https://github.com/dask/dask-gateway/issues/255.

And I've found in this issu some useful setting we might want to use: https://gateway.dask.org/api-server.html#c.ClusterConfig.idle_timeout.

We could specify this value to something like 30 minutes. Every cluster not doing any work during this time would be shutdown.

**Comment by tinaok** [comment]
Thank you, 
In this pull request 

https://github.com/pangeo-data/foss4g-2022/pull/87

 I added a cell which kills all their existing gateway cluster before they start a new one.
