### ISSUE TITLE
"Create bucket" un-responsive on the MinIO console

### ISSUE THREAD

**Issue by ofk123** [pangeo-data/pangeo-eosc#86]
Just thought about adding this issue on here.

I am logging in on the [MinIO console endpoint](https://pangeo-eosc-minio.vm.fedcloud.eu) with SSO (EGI-Check-in) 
In the "Buckets" site I choose a bucket-name which validates all the Bucket Naming Rules, not changing any features, and simply clicking ”Create Bucket”, which gives no response, and no visible error-message.

Does someone else also experience this? Or know how I can troubleshoot it better?
I do manage to create an Access Key, in the "Access Keys" site..

**Comment by sebastian-luna-valero** [comment]
Hi,

Before troubleshooting further, could you please have a look [at this example notebook](https://github.com/pangeo-data/pangeo-eosc/blob/15ff5d3622114d46a997e1669b6a3aa47e657c17/users/how-to/object-storage-minio-test.ipynb) on how to interact with MinIO?

Please note that the correct naming for your bucket must have this prefix `okihle-mybucket`.

**Comment by ofk123** [comment]
Using the `os.environ['JUPYTERHUB_USER']`as a prefix, lets me create a bucket. Thanks for the help!
