### ISSUE TITLE
Set sensible defaults for resources available for each trainee

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo-eosc#9]
Currently, in the pangeo-foss4g infrastructure, resources limit or default are as below:
- Jupyter notebook server : CPU: 2 guarantee, 4 maximum. Memory: 4G guarantee, 8G maximum.
- Dask gateway: not limit.
  - default values: 1CPU, 2GiB per worker
  - Max values: 4CPUS, 8GiB.
  - Not limit on number of workers (cluster.scale()).

From my point of view, we should limit notebook server to 2 CPUs, 4GB maximum (I don't think we need more?).

And on the Dask gateway side, we should use https://gateway.dask.org/resource-limits.html to at least fix some limits for each dask-gateway cluster created. Maybe 8 cores, 32GiB memory max?

I don't know yet a method to account for the occupancy of a Kubernetes cluster, but that probably exist. @sebastian-luna-valero or @j34ni any ideas? That could be handy to check wether our infrastructure is overloaded during training or not.

**Comment by guillaumeeb** [comment]
cc @annefou @acocac @tinaok @pl-marasco

**Comment by sebastian-luna-valero** [comment]
The deployment should include a [grafana dashboard](https://grafana.com/) to show accounting in real time. I believe @j34ni can provide you with access.

**Comment by sebastian-luna-valero** [comment]
In https://github.com/pangeo-data/pangeo-eosc/pull/10 I have set default values for the `values.yaml` that should match the resources available in the underlying cloud provider for the workshop. Please consider using these values.

**Comment by guillaumeeb** [comment]
I agree with the limits proposed by @sebastian-luna-valero. You can check them in his merged doc:
- https://github.com/pangeo-data/pangeo-eosc/blob/main/EGI.md?plain=1#L185
- https://github.com/pangeo-data/pangeo-eosc/blob/main/EGI.md?plain=1#L243
- https://github.com/pangeo-data/pangeo-eosc/blob/main/EGI.md?plain=1#L258

**Comment by guillaumeeb** [comment]
So on top of these limits, I would also configure an idle timeout for the cluster (see https://github.com/pangeo-data/pangeo-eosc/issues/8#issuecomment-1222679004).

We probably just need to add

```
        c.ClusterConfig..idle_timeout = 1800
```

to the yaml propose by @sebastian-luna-valero.

**Comment by sebastian-luna-valero** [comment]
Closing as obsolete. See:
* https://github.com/pangeo-data/pangeo-eosc/blob/main/providers/kubernetes/daskhub.yaml#L145
* https://github.com/pangeo-data/pangeo-eosc/blob/main/providers/kubernetes/daskhub.yaml#L178
* https://github.com/pangeo-data/pangeo-eosc/blob/main/providers/kubernetes/daskhub.yaml#L182
